### ISSUE TITLE
Incorrect Price Estimate

### ISSUE THREAD

**Issue by grabani** [AgentOps-AI/tokencost#14]
Hi

When I run the code:

```
from tokencost import calculate_prompt_cost, count_string_tokens

prompt_string = "Hello world" 
# response = "How may I assist you today?"
model= "gpt-3.5-turbo"

prompt_cost = calculate_prompt_cost(prompt_string, model)
print(count_string_tokens(prompt_string, model=model))
print(f"Cost: ${prompt_cost}/USD_PER_TPU")
```

I get the output:

`Cost: $30/USD_PER_TPU`

I was expecting to see something like` Cost: $2e-07` (as per the README)

**Comment by areibman** [comment]
Mistake in the documentation. Should be `print(f"Cost: ${prompt_cost/USD_PER_TPU}")`. Will fix shortly

**Comment by grabani** [comment]
I'm not sure your answer applies to this issue; but rather applies to [issue#13](https://github.com/AgentOps-AI/tokencost/issues/13).

Also, the solution your proposing is incorrect it should be `print(f"Cost: ${prompt_cost}/USD_PER_TPU")`

**Comment by grabani** [comment]
To solve this issue (explicitly for the function `calculate_prompt_cost`, is it a case of correcting the formula at line number:"[134](https://github.com/AgentOps-AI/tokencost/blob/123e4b3aa56d4ba834ff426aabc8250ff0cb56a6/tokencost/costs.py#L134C39-L135C1)" with the syntax `return (prompt_cost * prompt_tokens)/10000000` (you may define the denominator as a constant elsewhere.

**Comment by areibman** [comment]
Gotcha. I went ahead and updated the price. 

```
In [9]: from tokencost import calculate_prompt_cost, USD_PER_TPU
   ...:
   ...: prompt_string = "Hello world"
   ...: response = "How may I assist you today?"
   ...: model= "gpt-3.5-turbo"
   ...:
   ...: prompt_cost = calculate_prompt_cost(prompt_string, model)
   ...: print(f"Cost: ${prompt_cost/USD_PER_TPU}")
Cost: $3e-06
```
