### ISSUE TITLE
Please Check to see if the "pytest tests" pass successfully - I think the "USD_PER_TPU" variable may need importing 

### ISSUE THREAD

**Issue by grabani** [AgentOps-AI/tokencost#15]
Please Check to see if the "pytest tests" pass successfully - I think the "USD_PER_TPU" variable may need importing

**Comment by areibman** [comment]
```
============================= test session starts ==============================
platform darwin -- Python 3.8.16, pytest-7.4.3, pluggy-1.3.0
cachedir: .tox/py3/.pytest_cache
rootdir: /Users/reibs/Projects/tokencost
collected 79 items

tests/test_costs.py .................................................... [ 65%]
...........................                                              [100%]

============================== 79 passed in 0.98s ==============================
py3: commands[1]> coverage report -m
Name                     Stmts   Miss  Cover   Missing
------------------------------------------------------
tokencost/__init__.py        2      0   100%
tokencost/constants.py       3      0   100%
tokencost/costs.py          55      0   100%
------------------------------------------------------
TOTAL                       60      0   100%
py3: OK ✔ in 11.11 seconds
```

I'm showing full test coverage with `tax`. Can you show which tests are failing?

**Comment by grabani** [comment]
[tokencosts_test_results.txt](https://github.com/AgentOps-AI/tokencost/files/13790196/tokencosts_test_results.txt)

**Comment by areibman** [comment]
Can you verify you're on the latest version of the main branch? Something's up with your unit tests. For example:
```
__________________ test_count_string_tokens[gpt-3.5-turbo-4] __________________

model = 'gpt-3.5-turbo', expected_output = 4

    @pytest.mark.parametrize(
        "model,expected_output",
        [
            ("gpt-3.5-turbo", 4),
            ("gpt-3.5-turbo-0301", 4),
            ("gpt-3.5-turbo-0613", 4),
            ("gpt-3.5-turbo-16k", 4),
            ("gpt-3.5-turbo-16k-0613", 4),
            ("gpt-3.5-turbo-1106", 4),
            ("gpt-3.5-turbo-instruct", 4),
            ("gpt-4-0314", 4),
            ("gpt-4", 4),
            ("gpt-4-32k", 4),
            ("gpt-4-32k-0314", 4),
            ("gpt-4-0613", 4),
            ("gpt-4-1106-preview", 4),
            ("gpt-4-vision-preview", 4),
            ("text-embedding-ada-002", 4),
        ],
    )
    def test_count_string_tokens(model, expected_output):
        """Test that the string tokens are counted correctly."""
    
        # 4 tokens
>       assert count_string_tokens(STRING, model=model) == expected_output
E       AssertionError: assert 2 == 4
E        +  where 2 = count_string_tokens('Hello world', model='gpt-3.5-turbo')
```

There are no tests for the string `"Hello world"`. The string shared across test cases is `"Hello, world!"` (notice the punctuation marks). Did you modify the tests?

**Comment by grabani** [comment]
You are absolutely correct! As part of my troubleshooting for [issue#14](https://github.com/AgentOps-AI/tokencost/issues/14) I had modified the 'tests_cost.py' file.

I changed the string back to `"Hello, world!"` and all tests complete successfully:

I feel that I may have been more of a hinderance than a help 😔

```
============================================================================================== test session starts ==============================================================================================
platform win32 -- Python 3.11.3, pytest-7.4.3, pluggy-1.3.0
rootdir: C:\Users\xxx\OneDrive\Projects\Projects\chatgpt\tokencost-main\tokencost-main
plugins: anyio-3.7.1
collected 79 items

tests\test_costs.py ...............................................................................                                                                                                        [100%]

============================================================================================== 79 passed in 0.60s ===============================================================================================
```

**Comment by areibman** [comment]
> You are absolutely correct! As part of my troubleshooting for [issue#14](https://github.com/AgentOps-AI/tokencost/issues/14) I had modified the 'tests_cost.py' file.
> 
> I changed the string back to `"Hello, world!"` and all tests complete successfully:
> 
> I feel that I may have been more of a hinderance than a help 😔
> 
> ```
> ============================================================================================== test session starts ==============================================================================================
> platform win32 -- Python 3.11.3, pytest-7.4.3, pluggy-1.3.0
> rootdir: C:\Users\xxx\OneDrive\Projects\Projects\chatgpt\tokencost-main\tokencost-main
> plugins: anyio-3.7.1
> collected 79 items
> 
> tests\test_costs.py ...............................................................................                                                                                                        [100%]
> 
> ============================================================================================== 79 passed in 0.60s ===============================================================================================
> ```

No worries! You pointed out some issues with the readme, arguably the most important part of the library :) I appreciate the help
