### ISSUE TITLE
Make print optional in update_token_costs

### ISSUE THREAD

**Issue by augustfr** [AgentOps-AI/tokencost#35]
Right now the `update_token_costs` function in `tokencost/constants.py` has that print statement that always runs.

Makes me not want to use the package since whenever I run my program it prints that first. 

Maybe there should be a way to set a verbose bool and have it only print if verbose is set to true. I'd suggest having it default to false unless some function is imported and run to set it to true.

**Comment by areibman** [comment]
Would a verbosity arg on the function fix this? To what degree do you expect there to be no prints whatsoever?

**Comment by areibman** [comment]
@augustfr Take a look-- should be a good fix. We also started getting annoyed by the logs haha

https://github.com/AgentOps-AI/tokencost/pull/36
