### ISSUE TITLE
Expose calculate_cost_by_tokens

### ISSUE THREAD

**Issue by henrikhargedahl** [AgentOps-AI/tokencost#50]
In my scenario I like to use calculate_cost_by_tokens directly through import but I cannot do that because it is not added in tokencost/__init__.py. I suggest adding that to make it even more flexible in its usage.

**Comment by areibman** [comment]
> In my scenario I like to use calculate_cost_by_tokens directly through import but I cannot do that because it is not added in tokencost/**init**.py. I suggest adding that to make it even more flexible in its usage.

Sounds good/easy enough. Can you raise a PR for this?

**Comment by henrikhargedahl** [comment]
@areibman It's a very small change and of course I'd be happy to contribute. Could you add permissions to create a branch for this issue?

**Comment by areibman** [comment]
> @areibman It's a very small change and of course I'd be happy to contribute. Could you add permissions to create a branch for this issue?

Easiest way to do this is to fork the repo, create a branch on your fork, and then raise a pull request to this repo's main branch. Let me know if this works (I'm away from desktop atm)

**Comment by henrikhargedahl** [comment]
Done!

**Comment by areibman** [comment]
Closed with #54, thanks @henrikhargedahl !
