### ISSUE TITLE
Got-4o-mini

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/tokencost#64]
Upgrade to 4o mini

**Comment by nick-youngblut** [comment]
Any timeline on the next release, so that mini is supported in the pypi package?

**Comment by areibman** [comment]
> Any timeline on the next release, so that mini is supported in the pypi package?

It's available already without a new release since on-init the package fetches from this GitHub for the latest prices

**Comment by nick-youngblut** [comment]
I'm getting an error stating that gpt-4o-mini is not found
