### ISSUE TITLE
Support the Anthropic Token Counting API

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/tokencost#83]
Recent release: https://docs.anthropic.com/en/docs/build-with-claude/token-counting

We currently count tokens according to the GPT tiktoken tokenizer. We should use the API instead

**Comment by the-praxs** [comment]
Currently, we can update the `count_message_tokens` function to use this API.

`count_string_tokens` will use the old estimation.

**Comment by the-praxs** [comment]
> Currently, we can update the `count_message_tokens` function to use this API.
> 
> `count_string_tokens` will use the old estimation.

They removed `client.count_tokens` in version `0.39.0` ([Source](https://github.com/anthropics/anthropic-sdk-python/pull/726))
