### ISSUE TITLE
Jamba-instruct is not a valid model

### ISSUE THREAD

**Issue by areibman** [AgentOps-AI/tokencost#84]
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/addc4a94-2581-4d06-8dc7-25f686354f42">
We'll need to update Tokencost with Jamba-instruct. The model name in our dictionary is `ai21.jamba-instruct-v1:0`. Will raise an issue on that PR.

_Originally posted by @areibman in https://github.com/AgentOps-AI/agentops/issues/382#issuecomment-2454067449_

**Comment by the-praxs** [comment]
`jamba-instruct` is EOL on November 14, 2024. Do we still want to do this?

Source: https://docs.ai21.com/reference/jamba-instruct-api-ref
